name: Build Kivy APK

on:
  workflow_dispatch:   # για manual build
  push:
    branches:
      - main           # ή το branch σου

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-17-jdk unzip git \
            build-essential libffi-dev libssl-dev automake autoconf libtool pkg-config zlib1g-dev

          pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-kivy-app
          path: bin/*.apk
